### ISSUE TITLE
Hi, just asking something

### ISSUE THREAD

**Issue by AnIdiotsavant** [multimokia/MAS-Submod-Auto-Outfit-Change#1]
So you mentioned updating jsons. How do I do that?

**Comment by multimokia** [comment]
Simply head into the `Settings` menu, then into the `Submods` tab. Auto Outfit Change (Still Auto Hair Change in the submod settings menu for now) will have a button, `Update jsons`

Just hit that and it'll do it for you

**Comment by AnIdiotsavant** [comment]
Ahh okay! Thanks!!

**Comment by multimokia** [comment]
No problem!
