### ISSUE TITLE
Same outfit

### ISSUE THREAD

**Issue by CloakedGhost** [multimokia/MAS-Submod-Auto-Outfit-Change#10]
Hello,
I just wanna report that my Moni always chooses the same outfit, no matter what weather or if it's day or night (I have auto atmos installed).

**Comment by multimokia** [comment]
Sorry, been kinda busy. What outfits have you gifted her overall? It's possible you may only have one outfit type of the given criteria for the weather

**Comment by CloakedGhost** [comment]
Don't worry about it, I closed it because she does wear other outfits now (I updated the JSONS, maybe that fixed it). However her selection for outfits during the day seems to be a little small, for example the only "sunny weather" outfit she wore so far was the blue shirt. Other than that she only wore sweaters (even during the day) and the green hoodie. I have outfits like the sundress, wouldn't that also be used during the day if the weather is sunny?

**Comment by multimokia** [comment]
Unfortunately we don't have much to go for in those departments, it's mainly based on temperature vs the actual weather type. Though now that you've mentioned it, I kinda want a raincoat for her, haha.

But yeah it's revolving around temperature over the actual weather (rain/snow/sun/etc)

**Comment by CloakedGhost** [comment]
Oh I see thanks.
