### ISSUE TITLE
Ribbons never used automatically

### ISSUE THREAD

**Issue by LiminalityCarb** [multimokia/MAS-Submod-Auto-Outfit-Change#11]
I'm not sure why, but it seems like no matter what hairstyle is selected automatically, a Ribbon is never put on as well.  I have confirmed that the hairstyle JSON do have the ex_props  ribbon  set in them.

**Comment by multimokia** [comment]
She normally doesn't wear them indoors, but will typically wear them while heading out if you take her somewhere
