### ISSUE TITLE
OK, so, I have a really, really, *really specific* problem and issue:

### ISSUE THREAD

**Issue by YosefDreamer** [multimokia/MAS-Submod-Auto-Outfit-Change#21]
I want Monika to choose between the green hoodie, the school uniform with a blazer, the pink kimono and the white sundress during the day, change into her polka dot pink pajamas during the night, as well as I want her to be able to put on her default ponytail when it's daytime and to have her hair down when it's night-time.

How do I make the submod allow me to do that? I can't understand the coding, it's just too much when I look at it and it overwhelms me, I have the programming skills of a newbie.

**Comment by multimokia** [comment]
Hi there, thanks for reaching out.

Given the spritepack options, I have written out some documentation on ex_props and how they apply to clothes/hair and what each ones will do. You can see the file listing the docs [here](https://github.com/multimokia/MAS-Submod-Auto-Outfit-Change/blob/master/game/Submods/Auto%20Hair%20Change/ex_prop_explanation.md)

Now, given you want her to wear that inside, you'll want the `"home"` exprop for those clothes. For the PJs specifically, you won't want `"home"` but `"pajamas"` instead.

Given the builtin ones, (uniform), #5 provides some sample code on how to add the props to those outfits.

Looking at the documentation for hair as well, the ones you're already looking for are already in the day/night pool, unless you're looking to remove the spritepack ones, in which case you'll want to refer to [this map](https://github.com/multimokia/MAS-Submod-Auto-Outfit-Change/blob/master/game/Submods/Auto%20Hair%20Change/auto_hair_change.rpy#L120) in the code and change all the `True`s to `False` for the hair jsons, then hit the `update jsons` button in the submod's settings pane in MAS.

**Comment by multimokia** [comment]
Closing as resolved.
