### ISSUE TITLE
how do i change the outfits?

### ISSUE THREAD

**Issue by TheCheddarCheese** [multimokia/MAS-Submod-Auto-Outfit-Change#23]
i tried reading the explanation but i'm still not sure how to actually change them

**Comment by kaedeharaamla** [comment]
did you manage to find out? :3

**Comment by TheCheddarCheese** [comment]
> did you manage to find out? :3

yeah it needs to be added to the json file of the spritepack and it will pick one automatically (or at least it should, for some reason only the hair works for me)
