### ISSUE TITLE
Small question about customization

### ISSUE THREAD

**Issue by lunulae** [multimokia/MAS-Submod-Auto-Outfit-Change#5]
If I wanted to add a built-in outfit to the outfit selector, would I just add it into the lists such as `BUILTIN_HOME_CLOTHES` or are there additional steps?

Also, when the submod gets updates will I need to re-apply these changes?

Edit; Additionally, will this work for adding sweaters? I'd like to set it so she only wears her uniform with the blazer when it's cold.

**Comment by multimokia** [comment]
Alrighty, as of latest:

*store.ahc_utils.`add_builtin_to_list`* and *store.ahc_utils.`remove_builtin_from_list`* have been added
- The former allows you to add an item to one of the builtin lists, you can do this at `init 1 python`
- The latter allows you to remove an item from the builtin lists, likewise, this is also available at `init 1 python`
- These two functions take two arguments:
  1. `obj` - The `MASClothes`/`MASHair`/`MASAccessory` objects to add to a list
  2. `ex_prop` - The exprop corresponding to the list to match to.

Using an example of adding blazerless to home:
```renpy
init 1 python in ahc_utils:
    add_builtin_to_list(store.mas_clothes_blazerless, "home")
```
would do the trick.

This will not, however work for the sweater category. That can be done via directly adjusting an outfit's ex_props, though.

We'll assume we're using the same init block as last time:
```python
    store.mas_clothes_def.ex_props["sweater"] = None
```
Would do the trick to mark it as a sweater type.

**Comment by multimokia** [comment]
Closing as resolved
