### ISSUE TITLE
Not changing out of pajamas?

### ISSUE THREAD

**Issue by opalmew** [multimokia/MAS-Submod-Auto-Outfit-Change#7]
I installed this submod, but whenever my monika changes into her pajamas, she doesn't change out of them during the day. she only puts her hair down at night and up during the day. is this a bug or am i doing something wrong?

**Comment by multimokia** [comment]
What clothes does she have otherwise?

**Comment by opalmew** [comment]
> What clothes does she have otherwise?

The shoulderless sweater and pink shirt, are the two i can remember off the top of my head
